### ISSUE TITLE
fence instruction with two arguments

### ISSUE THREAD

**Issue by kasanari** [sifive/freedom-metal#111]
In the file [riscv_clint0.c](https://github.com/sifive/freedom-metal/blob/master/src/drivers/riscv_clint0.c) there is a call to `__METAL_IO_FENCE(o,i);` on line 188. This macro evaluates to `__asm__ volatile ("fence " #pred "," #succ ::: "memory");`. I can not find any explanation what the `fence` instruction with two register arguments does and am wondering what the purpose of this statement is.

**Comment by nategraff-sifive** [comment]
Hi @kasanari,

I recommend reading up on the fence instruction in the [RISC-V User Level ISA](https://riscv.org/specifications/), section 2.7 "Memory Model" on Page 20.

The main takeaway is that the arguments to the `fence` instruction aren't registers, they're types of memory system transactions (input, output, reads, and writes). The `fence` instruction is used to make sure that certain transactions prior to the`fence` complete before certain transactions after the `fence` are issued.

I hope this helps. If you have further questions, I recommend posting to somewhere like the [SiFive Forums](https://forums.sifive.com/), since that's a more appropriate venue.
